services:
  - type: web
    name: agrimart-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DEBUG
        value: false
