// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP2HEvJ3sKK3Hgpunk945ylP5gn0hshmE',
    appId: '1:346281612226:web:2d38e362de45ae198afc5b',
    messagingSenderId: '346281612226',
    projectId: 'agri-mart-add65',
    authDomain: 'agri-mart-add65.firebaseapp.com',
    storageBucket: 'agri-mart-add65.firebasestorage.app',
    measurementId: 'G-5Z5TZR2P9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpRidqxx4XggBiSZ6yEKGMJYLz7gcLQJk',
    appId: '1:346281612226:android:b8883d6df13d59e08afc5b',
    messagingSenderId: '346281612226',
    projectId: 'agri-mart-add65',
    storageBucket: 'agri-mart-add65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVL16XjMLgKJ2explqNFX00rphH_Z1PCU',
    appId: '1:346281612226:ios:d6aaae89bd0aee0f8afc5b',
    messagingSenderId: '346281612226',
    projectId: 'agri-mart-add65',
    storageBucket: 'agri-mart-add65.firebasestorage.app',
    iosClientId: '346281612226-657vbtg7k6is1973leg92a0jal8s1thr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVL16XjMLgKJ2explqNFX00rphH_Z1PCU',
    appId: '1:346281612226:ios:d6aaae89bd0aee0f8afc5b',
    messagingSenderId: '346281612226',
    projectId: 'agri-mart-add65',
    storageBucket: 'agri-mart-add65.firebasestorage.app',
    iosClientId: '346281612226-657vbtg7k6is1973leg92a0jal8s1thr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP2HEvJ3sKK3Hgpunk945ylP5gn0hshmE',
    appId: '1:346281612226:web:ce2be4c5f26f391b8afc5b',
    messagingSenderId: '346281612226',
    projectId: 'agri-mart-add65',
    authDomain: 'agri-mart-add65.firebaseapp.com',
    storageBucket: 'agri-mart-add65.firebasestorage.app',
    measurementId: 'G-8328F0W812',
  );

}