// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOuP86cXSCCe3wXoulXP_2ASoRxgjNa38',
    appId: '1:525427975450:web:74f96c7fe08bdba2c6b8a3',
    messagingSenderId: '525427975450',
    projectId: 'connect-model',
    authDomain: 'connect-model.firebaseapp.com',
    storageBucket: 'connect-model.firebasestorage.app',
    measurementId: 'G-CZNTGSP2HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRxfdD14MRcRVbqDueB3eW-wv3HJURk4',
    appId: '1:525427975450:android:660b3885c6fe9847c6b8a3',
    messagingSenderId: '525427975450',
    projectId: 'connect-model',
    storageBucket: 'connect-model.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6AXvlt4-m6W5pH6oA7OEr2Pl1Z-xtpU',
    appId: '1:525427975450:ios:ce517d261443654dc6b8a3',
    messagingSenderId: '525427975450',
    projectId: 'connect-model',
    storageBucket: 'connect-model.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV6AXvlt4-m6W5pH6oA7OEr2Pl1Z-xtpU',
    appId: '1:525427975450:ios:ce517d261443654dc6b8a3',
    messagingSenderId: '525427975450',
    projectId: 'connect-model',
    storageBucket: 'connect-model.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOuP86cXSCCe3wXoulXP_2ASoRxgjNa38',
    appId: '1:525427975450:web:5e306aeee2874d83c6b8a3',
    messagingSenderId: '525427975450',
    projectId: 'connect-model',
    authDomain: 'connect-model.firebaseapp.com',
    storageBucket: 'connect-model.firebasestorage.app',
    measurementId: 'G-HWC1EFQV7Z',
  );
}
