import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';  // Import Firebase Core
import 'package:namer_app/ChatScreen/chat_screen.dart';
import 'package:namer_app/Presentation/Price_analysis.dart';
import 'package:namer_app/Presentation/first_screen/Login.dart';
import 'package:namer_app/Presentation/first_screen/first_screen.dart';
import 'ChatScreen/chat_list_page.dart';
import 'firebase_options.dart';  // This file will be generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();  // Ensure Flutter is ready before Firebase is initialized.
  
  // Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,  // Firebase options generated by flutterfire configure
  );
  
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int count = 0;
  Color _scaffoldColor = Colors.white;
  double _isVisible = 0.0;
  String _nameToChange = "flow";
  String _inputText = "";
  int _hours=0;
  final ScrollController _scrollController = ScrollController(); // Step 1: Declare ScrollController

  void numbers() {
    setState(() {
      count++;
    });
  }

  void changeColor() {
    setState(() {
      _scaffoldColor = _scaffoldColor == Colors.black12 ? Colors.blue : Colors.black12;
    });
  }

  void changeVisibility() {
    setState(() {
      _isVisible = _isVisible == 1.0 ? 0.0 : 1.0;
    });
  }

  void changeName() {
    setState(() {
      _nameToChange = _nameToChange == "flow" ? "rukaass" : "flow";
    });
  }

  void changeHour() {
    setState(() {
      _hours++;
    });
  }

  @override
  void dispose() {
    _scrollController.dispose(); // Dispose the controller to prevent memory leaks
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: ChatListPage(),  // Your home screen
    );
  }
}
