name: Flutter CI/CD with Chrome Testing

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend # Set the working directory for all steps

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # Specify your Flutter version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Run Unit Tests on Chrome
      - name: Run Flutter Unit Tests on Chrome
        run: |
          echo "Running unit tests on Chrome..."
          flutter test --platform chrome --coverage

      # Step 5: Run Widget Tests on Chrome
      - name: Run Flutter Widget Tests on Chrome
        run: |
          echo "Running widget tests on Chrome..."
          flutter test --platform chrome test/widget_test.dart

      # Step 6: Run Integration Tests on Chrome
      - name: Run Flutter Integration Tests on Chrome
        run: |
          echo "Running integration tests on Chrome..."
          flutter test --platform chrome integration_test/app_test.dart

      # Step 7: Decode Keystore
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # Step 8: Build the Flutter app
      - name: Build Android APK
        run: flutter build apk --release
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      # Step 9: Deploy to Firebase App Distribution
      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }} # Firebase App ID
          token: ${{ secrets.FIREBASE_TOKEN }} # Firebase CI token
          testers: rukshancoc@gmail.com # Add your email as a tester
          file: build/app/outputs/flutter-apk/app-release.apk # Path to the APK