name: Flutter CI/CD to Firebase App Distribution

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # Specify your Flutter version

      # Step 3: Navigate to the Flutter project directory
      - name: Navigate to Flutter project directory
        run: cd Frontend

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          cd Frontend
          flutter pub get

      # Step 5: Run tests
      - name: Run Flutter tests
        run: |
          cd Frontend
          flutter test

      # Step 6: Build the Flutter app
      - name: Build Android APK
        run: |
          cd Frontend
          flutter build apk --release

      # Step 7: Deploy to Firebase App Distribution
      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }} # Firebase App ID
          token: ${{ secrets.FIREBASE_TOKEN }} # Firebase CI token
          groups: testers # Firebase App Distribution tester group
          file: Frontend/build/app/outputs/flutter-apk/app-release.apk # Path to the APK
