name: Flutter CI/CD to Firebase App Distribution

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend # Set the working directory for all steps

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Run Flutter Unit Tests
      - name: Run Flutter Unit Tests
        run: flutter test --coverage

      # Step 5: Run Flutter Widget Tests
      - name: Run Flutter Widget Tests
        run: flutter test test/widget_test.dart

      # Step 6: Run Flutter Integration Tests
      - name: Run Flutter Integration Tests
        run: flutter test integration_test/app_test.dart

      # Step 7: Decode Keystore
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # Step 8: Build the Flutter app
      - name: Build Android APK
        run: flutter build apk --release
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      # Step 9: Deploy to Firebase App Distribution
      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          testers: rukshancoc@gmail.com
          file: build/app/outputs/flutter-apk/app-release.apk