name: Flutter CI/CD to Firebase App Distribution

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # Specify your Flutter version

      # Step 3: Navigate to the Flutter project directory
      - name: Navigate to Flutter project directory
        run: cd Frontend

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          cd Frontend
          flutter pub get

      # Step 5: Decode Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > Frontend/android/app/upload-keystore.jks

      # Step 6: Build the Flutter app
      - name: Build Android APK
        run: |
          cd Frontend
          flutter build apk --release
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      # Step 7: Deploy to Firebase App Distribution (With Tester Email)
      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }} # Firebase App ID
          token: ${{ secrets.FIREBASE_TOKEN }} # Firebase CI token
          testers: rukshancoc@gmail.com # Add your email as a tester
          file: Frontend/build/app/outputs/flutter-apk/app-release.apk # Path to the APK
